### ISSUE TITLE
Please delete private information.

### ISSUE THREAD

**Issue by ptnhan109** [sagarpatil94/IMPFunctionNetCore#1]
Hi @sagarpatil94.
I'm nhan1110i, I created this source code, please help me delete username, password and url in 2 files Account.cs and Url.cs
my email : trongnhan1110i@gmail.com

**Comment by sagarpatil94** [comment]
i deleted your 2 files ok

**Comment by ptnhan109** [comment]
@sagarpatil94 many thank sir. Have nice a day :D
